name: Build and Push to Docker Hub

on:
  push:
    branches: [develop, staging]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  # IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}  # <--- importante
  IMAGE_NAME: joseco/mi-app-python

jobs:
  build-and-push:
    runs-on: [self-hosted]
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Define TAG
      run: echo "TAG=${{ github.run_number }}.${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Build and Push Image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

    # - name: Build Docker (local test)
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     load: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}
    - name: Stop Previous Services
      run: docker compose down -v || true

    - name: Running Container Tests
      run: |
        IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ env.TAG }}
        echo "Usando imagen: $IMAGE_TAG"
        docker run -d --name test-container -p 5000:5000 $IMAGE_TAG
        trap "docker stop test-container && docker rm test-container" EXIT
        sleep 10
        curl -f http://localhost:5000/health
