name: Build and Push to Docker Hub

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}  # <--- importante

jobs:
  build-and-push:
    runs-on: [self-hosted]
    permissions:
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login a Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Definir TAG
      run: echo "TAG=${{ github.run_number }}.${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Build Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

    # - name: Build Docker (local test)
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     load: true
    #     tags: ${{ steps.meta.outputs.tags }}
    #     labels: ${{ steps.meta.outputs.labels }}

    - name: Testear contenedor
      run: |
        IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ env.TAG }}
        echo "Usando imagen: $IMAGE_TAG"
        docker run -d --name test-container -p 5000:5000 $IMAGE_TAG
        sleep 10
        curl -f http://localhost:5000/health
        docker stop test-container && docker rm test-container

    - name: Push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        # tags: ${{ steps.meta.outputs.tags }}
        # labels: ${{ steps.meta.outputs.labels }}
