name: Deploy con Docker Compose

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: [self-hosted]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Parar servicios anteriores
      run: docker compose down -v || true

    - name: Construir servicios
      run: docker compose -f docker-compose.yml build

    - name: Levantar servicios
      run: docker compose -f docker-compose.yml up -d

    - name: Verificar app
      run: curl -f http://localhost:5000/health
  
  check-app:
    runs-on: [self-hosted]
    needs: deployment
    steps:
    - name: Chequear estado
      run: |
        curl -f http://localhost:500/health && echo "✅ App OK" || echo "❌ App caída"
    
    - name: Logs de servicios (Si falla)
      if: failure()
      run: docker compose logs --tail=50