name: Deploy con Docker Compose

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  deployment:
    runs-on: [self-hosted]

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Parar servicios anteriores
      run: docker compose down -v || true

    - name: Construir servicios
      run: docker compose -f docker-compose.yml build

    - name: Levantar servicios
      run: docker compose -f docker-compose.yml up -d

    - name: Verificar app
      run: curl -f http://localhost:5000/health
  
  check-app:
    runs-on: [self-hosted]
    steps:
    - name: Chequear estado
      run: |
        curl http://localhost:5000/health && echo "✅ App OK" || echo "❌ App caída"